spring:
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  override-with-generic-response: false
