# Server configuration
server:
  port: 8081
  servlet:
    context-path: /profiles

# Default Spring configuration
spring:
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
  profiles:
    active: prod

# Logging configuration
logging:
  level:
    root: INFO

# Dev profile
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  sql:
    init:
      mode: always
      encoding: utf-8
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql


# Prod profile
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:5433/profiles
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: profiles
